### ISSUE TITLE
Design dashboard using bootstrap 4

### ISSUE THREAD

**Issue by kiranshahi** [kiranshahi/e-grihakarya#25]

**Comment by davivaldi** [comment]
which exact file do you need help with designing im helping a little for hackathon

**Comment by rakeshlanjewarwork** [comment]
why you are trying to use bootstrap ?

You can use angular material instead.
Reply this issue , i would like to contribute.

**Comment by kiranshahi** [comment]
I want to use bootstrap because I want to reduce dependency of node module.

**Comment by rakeshlanjewarwork** [comment]
i am trying to setup the environment. 
But the project is old

**Comment by kiranshahi** [comment]
@rakeshlanjewarwork check out to `dev-env` branch
